apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tpregisteret
  namespace: {{namespace}}
  labels:
    team: teampeon
spec:
  image: repo.adeo.no:5443/tpregisteret:{{version}}
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/tpregisteret/default
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: oracle/data/dev/creds/tjenestepensjon_q0-user/password
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus