apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tpregisteret
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://tpregisteret.nais.preprod.local
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
    paths:
      - mountPath: /secrets/oracle
        kvPath: oracle/data/dev/creds/tjenestepensjon_q0-user
  webproxy: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
