management:
  endpoint.prometheus.enabled: true
  endpoints.web.exposure.include: prometheus, health
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    continue-on-error: false
logging.level.no.nav.peproxy: INFO