management:
  endpoint:
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus, health
no.nav.security.jwt:
        issuer:
          maskinporten:

logging:
  level:
    no:
      nav:
        peproxy: INFO