no.nav.security.jwt.issuer:
  maskinporten:
    discoveryurl: https://maskinporten.no/.well-known/oauth-authorization-server
    proxyurl: http://webproxy.nais:8088/
  sts:
    discoveryUrl: http://security-token-service/.well-known/openid-configuration
    accepted_audience: preprod.local,srvpensjon